### ISSUE TITLE
Graph is not accurate with the data while spamming

### ISSUE THREAD

**Issue by unbounded26** [monitor1394/unity-ugui-XCharts#163]
I'm using [XCharts-2.3.0-upm.unitypackage](https://github.com/monitor1394/unity-ugui-XCharts/releases/tag/v2.3.0) 

1. Bug - Spamming
The graph displayed is wrong according to passed and displayed data, if you spam on displaying the graph. While it shows perfectly fine if the showing graph button is not spammed.

I'm doing `_lineChart.ClearData();` before populating graph again and `_lineChart.RefreshChart();` after adding every entry in the graph
<img width="448" alt="Screenshot 2021-08-13 at 4 18 42 PM" src="https://user-images.githubusercontent.com/7029364/129328713-1ead8423-da40-4fea-a190-32e2a1f0e15b.png">
<img width="743" alt="Screenshot 2021-08-13 at 4 19 26 PM" src="https://user-images.githubusercontent.com/7029364/129328749-d76092b8-a01c-4cc6-885a-d0b4e43fd917.png">
<img width="737" alt="Screenshot 2021-08-13 at 4 19 47 PM" src="https://user-images.githubusercontent.com/7029364/129328768-c47625f7-10fc-4e03-8556-3a85b646d211.png">
Above data remains the same, and the graph should be
<img width="375" alt="Screenshot 2021-08-13 at 4 18 30 PM" src="https://user-images.githubusercontent.com/7029364/129328839-9482ade6-48e1-43b3-bafa-7365ad2fe70c.png">
While I also get the following variations of the graph by spamming the show graph button with the same above mentioned data
<img width="373" alt="Screenshot 2021-08-13 at 4 27 41 PM" src="https://user-images.githubusercontent.com/7029364/129328951-503d7cbb-ac66-4f3e-9c32-b4e7b1720ff7.png">
<img width="368" alt="Screenshot 2021-08-13 at 4 28 00 PM" src="https://user-images.githubusercontent.com/7029364/129328963-924a45b4-5a14-4a3d-8e7b-f3f95bc4d64f.png">

2. Bug - Y-axis arrow needs to point upwards
<img width="57" alt="Screenshot 2021-08-13 at 4 20 28 PM" src="https://user-images.githubusercontent.com/7029364/129328986-26e019ec-cc07-4487-ab57-20608e8dd650.png">

3. UI - Legend text should match the line color to be obvious and easy to understand
4. UI - The selected color of the line and the point should be the same, while it is reversed. And Point color can't be set, better to be the same as the line
5. UI - X-axis label don't stay with the x-axis on zoom, when there is a lot of data and rotation is applied

**Comment by monitor1394** [comment]
> While I also get the following variations of the graph by spamming the show graph button with the same above mentioned data

I don't understand your question yet. What did you do when you clicked the Spamming button？

> Bug - Y-axis arrow needs to point upwards

How did you set for the point downward?

> UI - Legend text should match the line color to be obvious and easy to understand

You can change the theme ColorPalettle

> UI - The selected color of the line and the point should be the same, while it is reversed. And Point color can't be set, better to be the same as the line

Also you can change the theme ColorPalettle. itemStyle color can set for point color, lineStyle color can set for line color.

> UI - X-axis label don't stay with the x-axis on zoom, when there is a lot of data and rotation is applied

Can you show some screenshots? I don't understand the question yet.

**Comment by unbounded26** [comment]
> > While I also get the following variations of the graph by spamming the show graph button with the same above mentioned data
> 
> I don't understand your question yet. What did you do when you clicked the Spamming button？
> 
I mean if I press Show Graph button multiple times quickly without changing the data

> > Bug - Y-axis arrow needs to point upwards
> 
> How did you set for the point downward?
> 
I don't know, as I just checked the y-axis arrow and it shows a downward arrow for y-axis, while x-axis is correct as expected

> > UI - Legend text should match the line color to be obvious and easy to understand
> 
> You can change the theme ColorPalettle
> 
ColorPalette under theme don't specify which color will change the Legend text. Also
> * (2021.08.14) Added `Legend`'s `textAutoColor` to set the text color match with `Serie` color (#163)

This one won't work as the above screenshots show. 

> > UI - The selected color of the line and the point should be the same, while it is reversed. And Point color can't be set, better to be the same as the line
> 
> Also you can change the theme ColorPalettle. itemStyle color can set for point color, lineStyle color can set for line color.
> 

Under where? as I already changed it
> > UI - X-axis label don't stay with the x-axis on zoom, when there is a lot of data and rotation is applied
> 
> Can you show some screenshots? I don't understand the question yet.

Here is the screenshot of graph (with same data as mentioned above) with zoom-in
<img width="247" alt="Screenshot 2021-08-14 at 10 30 23 PM" src="https://user-images.githubusercontent.com/7029364/129449652-4f254c36-c81f-4915-92e9-d7d73767f99a.png">


Also, your source code and Plugin don't match, so which one is latest?

**Comment by monitor1394** [comment]
The master branch is latest. 
The release version will be released when the master is stable. So usually release version is behind the master.

**Comment by unbounded26** [comment]
Yes, I updated the code to master branch.

Now, **_Issue 1 & 2, still exists_**. While others are resolved.
Issue 1 is more major, as it totally changes the graph, even if tapping with some delay on ShowGraph button with same data

**Comment by monitor1394** [comment]
Issue 1 has been fixed in the latest master branch. 
But Issue 2 I don't know why yet, I can't reproduce it.

**Comment by unbounded26** [comment]
Thanks a lot, yes Issue 1 is fixed. Still, Issue 2 exists, but I'm not using the arrows in my project, so you can take your time to fix it.

By the way, I haven't done anything fancy, which made the arrow downward. I just checked to see the arrow on the y-axis and it wasn't as expected (as shown in the picture)

**Comment by unbounded26** [comment]
I was working on it and found another bug related to [d87e0f8](https://github.com/monitor1394/unity-ugui-XCharts/commit/d87e0f8267cef080a77a896cd2673ea774d3b4ae) that if the y-data is 0, x-axis label doesn't update itself, while the data is as expected.

This is the expected data which is in the x-data with 0 value on y-axis
<img width="497" alt="Screenshot 2021-08-20 at 1 14 41 AM" src="https://user-images.githubusercontent.com/7029364/130114399-34c7eb3a-ac63-4030-848d-4635f6312b04.png">

The unchanged x-axis label
<img width="303" alt="Screenshot 2021-08-20 at 1 15 02 AM" src="https://user-images.githubusercontent.com/7029364/130114537-923476f8-2d78-47a8-9a27-6f1e7856b3b5.png">

So update is still missing in some places in the code

**Comment by unbounded26** [comment]
Yeah, I'm using the latest code, still facing the above mentioned issue

**Comment by unbounded26** [comment]
The following video explains the issue more clearly, as you can see the dates which I'm showing in the graph with 3 months patches

https://user-images.githubusercontent.com/7029364/130215961-432f4467-afea-4c90-abbf-142df59d739e.mov
Only the first and the last click change the x-axis label as only data available is in that portion, while you can see I have 3 months of gap graph to show. In middle, I have no data, so the x-axis label doesn't update, while according to x-axis data it is updated (as the screenshot previously shared shows inspector)

**Comment by monitor1394** [comment]
What do you do when you click the left and right buttons？Can you show me the relevant code？
By the way, you can manually refresh the axis with codes:
`xAxis.SetAllDirty();`

**Comment by unbounded26** [comment]
`_lineChart.xAxis0.SetAllDirty();` This also didn't work to update the x-axis label. Shared video is better to understand the issue.

`// styling`
`_lineChart.xAxis0.axisLabel.textStyle.offset = new Vector2(0, -95f);`
`_lineChart.xAxis0.axisLabel.textStyle.rotate = 90f;`
`_lineChart.RefreshChart();`

`// populate data`
`_lineChart.AddXAxisData(dateToString("dd/MM/yy"));`
`_lineChart.AddData(0, GREEN_VALUE);`
`_lineChart.AddData(1, ORANGE_VALUE);`
`_lineChart.xAxis0.SetAllDirty();`
`_lineChart.RefreshChart();`

I'm simply using the above sample code every time to show the graph with respective data of 3 months (as I know for 1 or 2 years data is too big to show on one graph). Arrows just fetch the next or previous data to populate.

Kindly fix this issue, as I'm stuck in this, as with wrong data on the graph I can't submit my app

**Comment by monitor1394** [comment]
I have fixed it in 2.0 branch.
If you need to use the latest code, you'll need to switch to the 2.0 branch and download it.

**Comment by unbounded26** [comment]
Yeah, thanks a lot. Issue 1 is fixed
